/**
 * Local storage store name, this is prefixed to all async store keys.
 * @var string
 */
export const STORE_NAME = "@TOPSUN";

/**
 * List of available async store keys
 */
export const STORE_KEYS = {
  AUTHENTICATED: STORE_NAME + "@AUTHENTICATED",
  THEME: STORE_NAME + "@THEME",
  USER_DETAILS: STORE_NAME + "@USER_DETAILS",
  USER_ACCESS_TOKEN: STORE_NAME + "@USER_ACCESS_TOKEN",
  USER_REFRESH_TOKEN: STORE_NAME + "@USER_REFRESH_TOKEN",
  ACTIVE_SESSION_DATA: STORE_NAME + "@ACTIVE_SESSION_DATA",
  CLASS_LEVEL_DATA: STORE_NAME + "@CLASS_LEVEL_DATA",
  EXAM_TIMETABLE: STORE_NAME + "@EXAM_TIMETABLE",
  OBJ_EXAM_RESULT: STORE_NAME + "@OBJ_EXAM_RESULT",
  LANGUAGE_STORAGE_KEY: STORE_NAME + "@LANGUAGE_STORAGE_KEY",
  TEMP_USER_TYPE: STORE_NAME + "@USER_TYPE",
  REMEMBER_ME_EMAIL_KEY: STORE_NAME + "@REMEMBER_ME_EMAIL",
  REMEMBER_ME_PASSWORD_KEY: STORE_NAME + "@REMEMBER_ME_PASSWORD",
};
